---
- hosts: web
  become: yes
  tasks:
  - name: Install Apache
    yum: name=httpd state=present
  - name: Ensure Apache is running
    service: name=httpd state=started enabled=yes
  - name: Install php-gd
    yum: name=php-gd state=present